panels:
  1:
    position: [0.1, 0.4]
    field : [
        [0.1, 0.6],
        [3.6, 0.6],
        [3.6, 4.0],
        [0.1, 4.0],
        [0.1, 0.6]
    ]
  2:
    position: [4.2, 0.4]
    field: [
        [4.2, 0.6],
        [7.7, 0.6],
        [7.7, 4.0],
        [4.2, 4.0],
        [4.2, 0.6]
    ]
  3:
    position: [8.3, 0.4]
    field: [
        [8.3, 0.6],
        [15.8, 0.6],
        [15.8, 4.0],
        [8.3, 4.0],
        [8.3, 0.6]
    ]


