panels:
  1:
    position: [0.1, 0.4]
    field : [
        [0.1, 0.4],
        [3.8, 0.4],
        [3.8, 3.8],
        [0.2, 3.8],
        [0.1, 0.4]
    ]
  2:
    position: [x2, y2]
    field: [
        [0.1, 0.4],
        [3.8, 0.4],
        [3.8, 3.8],
        [0.2, 3.8],
        [0.1, 0.4]
    ]
  3:
    position: [x3, y3]
    field: [
        [0.1, 0.4],
        [3.8, 0.4],
        [3.8, 3.8],
        [0.2, 3.8],
        [0.1, 0.4]
    ]
  4:
    position: [x4, y4]
    field: [
        [0.1, 0.4],
        [3.8, 0.4],
        [3.8, 3.8],
        [0.2, 3.8],
        [0.1, 0.4]
    ]
docking_station: [x0, y0]
