coverage_server:
  ros__parameters:
    use_sim_time: True

    # Your robot’s size & behavior
    robot_width: 0.18  # Actual TurtleBot3 Waffle width in meters
    operation_width: 0.18  # Equal to robot width if no extra cleaning tool
    min_turning_radius: 0.10  # Tight turning radius, TurtleBot3 is capable

    # Headland: buffer zone around field border
    default_headland_width: 0.10  # Smaller since the robot is small, but still adds margin from edges

    # Controls smoothness of curvature changes
    linear_curv_change: 50.0  # Lower = smoother curve transitions for small robots

    # Frame and overlap
    coordinates_in_cartesian_frame: true
    default_allow_overlap: false  # Set to true if you want redundant cleaning for safety

    # Swath angle: direction of coverage
    default_swath_angle_type: "SET_ANGLE"
    default_swath_angle: 0.0  # 0 rad = sweep along X-axis (horizontal). Adjust depending on panel layout

# coverage_server:
#   ros__parameters:
#     use_sim_time: True
#     default_headland_width: 0.25
#     robot_width: 0.7
#     operation_width: 0.7
#     min_turning_radius: 0.35
#     linear_curv_change: 200.0
#     coordinates_in_cartesian_frame: true
#     default_allow_overlap: false
#     default_swath_angle_type: "SET_ANGLE"
#     default_swath_angle: 0.0 # We know its aligned for the demo