twist_mux:
  ros__parameters:
    use_stamped: false
    topics:
      teleop:
        topic: /cmd_vel/teleop
        timeout : 0.5
        priority: 10   # lower
      nav2:
        topic: /cmd_vel/nav
        timeout : 0.5
        priority: 30   # higher
      go_to_pose:
        topic: /cmd_vel/go_to_pose
        timeout : 0.5
        priority: 20   # highest
